// Builds the local denylist of personal terms used by scripts/checkPrivateData.ts
// (the pre-push guard, CLAUDE.md deep-review-2026-09-26.md finding S1). Pure - no
// DB, no filesystem - so it's easy to test. The output is written to the
// gitignored data-private/private-terms.txt by scripts/ingestSavedVariables.ts,
// since that script already has every source of names in memory (parsed
// straight from local SavedVariables files) and already runs locally, never in
// CI. Terms: character names (roster/sales/purchases/stock/gold), guild names (gold) and counterparty
// (buyer/seller) names, plus the WTF account folder id from
// earningsAccounts.local.json - the same composition the manual scan in
// deep-review-2026-09-26.md (finding S1) used and proved workable (140 terms,
// no false-positive flood). None of these are ever committed themselves -
// only used here to build a list of strings that must never appear in a
// commit.
//
// Deliberately EXCLUDED, both tried and reverted:
//   - realm names: CLAUDE.md #16 says the player's roster spans 81 of the 92
//     EU connected-realm clusters, so almost any real WoW realm name
//     mentioned anywhere (a code comment's example, a test fixture) matches
//     by pure coincidence. Turned the guard red on nearly every push.
//   - the account LABEL (human display name, e.g. "Account 1"): low
//     sensitivity - CLAUDE.md #13 identifies the FOLDER (the actual
//     Battle.net identifier) as the sensitive part, not the label Simon picked
//     to show in reports - and a generic label collides with the example
//     placeholders in config/earningsAccounts.example.json.
// If either is ever needed again, split it out as its own opt-in category
// rather than lumping it back into the default set - don't just revert this.
//
// Matching later is whole-word, case-insensitive (see checkPrivateData.ts), so
// a short common word turning up as a "private term" would produce useless
// noise - hence MIN_TERM_LENGTH. Terms are kept as the FULL string only, never
// split into individual words (words() was tried and reverted for the same
// reason as realm names above: it turns a multi-word name into ordinary
// English word fragments).
import type { ExtractedAccountData } from "../earnings/savedVariables.js";
import type { EarningsAccount } from "../../config/earningsAccounts.js";

const MIN_TERM_LENGTH = 4;

function addTerm(set: Set<string>, raw: string | null | undefined): void {
  if (!raw) return;
  const trimmed = raw.trim();
  if (trimmed.length >= MIN_TERM_LENGTH) set.add(trimmed);
}

export interface AccountDataSource {
  data: ExtractedAccountData;
}

/**
 * Collects every distinct personal term (character name, buyer, seller, WTF
 * account folder id) from the accounts' already-parsed SavedVariables data
 * plus the earnings account config, deduped case-insensitively. Returns terms
 * in their original casing, sorted. Deliberately excludes realm names and the
 * account label - see the file comment above.
 */
export function collectPrivateTerms(
  accounts: AccountDataSource[],
  earningsAccounts: EarningsAccount[] = [],
): string[] {
  const seenLower = new Map<string, string>(); // lowercase -> first-seen original casing

  const add = (raw: string | null | undefined) => {
    const set = new Set<string>();
    addTerm(set, raw);
    for (const t of set) {
      const lower = t.toLowerCase();
      if (!seenLower.has(lower)) seenLower.set(lower, t);
    }
  };

  for (const a of accounts) {
    for (const s of a.data.sales) {
      add(s.characterName);
      add(s.buyer);
    }
    for (const p of a.data.purchases) {
      add(p.characterName);
      add(p.seller);
    }
    for (const r of a.data.roster) {
      add(r.characterName);
    }
    for (const o of a.data.stockObservations) {
      add(o.characterName);
    }
    for (const h of a.data.stockHeld) {
      add(h.characterName);
    }
    // Gold sources: character names and GUILD names (a guild name identifies
    // the player just as well; realm names stay excluded, see above).
    for (const g of a.data.goldObservations) {
      add(g.name);
    }
  }

  for (const ea of earningsAccounts) {
    add(ea.folder);
  }

  return [...seenLower.values()].sort((a, b) => a.localeCompare(b));
}

export const PRIVATE_TERMS_HEADER =
  "# Auto-generated by `npm run ingest` from local SavedVariables files. Gitignored.\n" +
  "# One term per line, case-insensitive whole-word match. See scripts/checkPrivateData.ts.\n" +
  "# Do not hand-edit; add durable placeholders to config/earningsAccounts.example.json instead.\n";

export function formatPrivateTermsFile(terms: string[]): string {
  return PRIVATE_TERMS_HEADER + terms.join("\n") + (terms.length > 0 ? "\n" : "");
}
