/**
 * Personal-data guard for this public repo (deep-review-2026-09-26.md, finding
 * S1). Scans what's about to be pushed - added diff lines and commit messages
 * in the range being pushed - for:
 *   - every term in the local, gitignored data-private/private-terms.txt
 *     (regenerated by `npm run ingest` from real character/buyer/seller names
 *     and the WTF account folder id - deliberately NOT realm names or the
 *     account label, see src/privacy/privateTerms.ts for why);
 *   - the folder/label in config/earningsAccounts.local.json directly, in case
 *     the terms file is stale or was never generated;
 *   - a few generic, repo-independent patterns: a Battle.net-style account id
 *     (digits#digits), a `WTF\Account\<real folder>` path, and a committed
 *     SavedVariables file;
 *   - any staged/pushed path matching a pattern .gitignore already excludes
 *     (*.sqlite, *.log, reports-private/, data-private/, the local earnings
 *     account config) - catches a `git add -f` bypass.
 *
 * Usage:
 *   Installed as .githooks/pre-push (enable once with
 *   `git config core.hooksPath .githooks`), invoked by git with no args and
 *   the standard pre-push stdin protocol: lines of
 *   "<local ref> <local sha1> <remote ref> <remote sha1>".
 *
 *   For manual testing:
 *     npx tsx scripts/checkPrivateData.ts --range <a>..<b>
 *     npx tsx scripts/checkPrivateData.ts --staged   # git diff --cached only, no commit messages
 *
 * Exit code 1 and a file:line (or commit) report on any hit, masking the
 * matched text; exit 0 otherwise. This only ever reads from git and the local
 * filesystem - it makes no commits, pushes nothing, and calls no network.
 */
import { existsSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const PRIVATE_TERMS_PATH = fileURLToPath(new URL("../data-private/private-terms.txt", import.meta.url));
const LOCAL_ACCOUNTS_PATH = fileURLToPath(new URL("../config/earningsAccounts.local.json", import.meta.url));
const EMPTY_TREE = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"; // git's fixed empty-tree object id
const ALL_ZERO = "0000000000000000000000000000000000000000";

const FORBIDDEN_PATH_PATTERNS: RegExp[] = [
  /\.sqlite$/i,
  /\.sqlite-(wal|shm|journal)$/i,
  /\.log$/i,
  /^reports-private\//,
  /^data-private\//,
  /^config\/earningsAccounts\.local\.json$/,
  // An actual WoW SavedVariables file (a real player's data), wherever it
  // sits in the tree - not just under WTF\Account, in case one gets copied
  // somewhere else first.
  /[\\/]SavedVariables[\\/].*\.lua$/i,
];

// Generic, repo-independent - these don't need the local denylist to catch.
const GENERIC_PATTERNS: { label: string; re: RegExp }[] = [
  { label: "Battle.net-style account id (digits#digit)", re: /\b\d{6,}#\d\b/ },
  {
    label: "WTF\\Account path with a real folder name",
    // Excludes placeholder/prose continuations: REPLACE_WITH_..., <...>, a
    // literal "...", a unicode ellipsis "…", a closing backtick/quote/paren,
    // or end of line - i.e. "WTF\Account\" used descriptively, not followed
    // by an actual folder name.
    re: /WTF[\\/]Account[\\/](?!REPLACE_WITH_|<|\.\.\.|…|[`'")]|\s|$)\S+/,
  },
  // Deliberately no free-text "mentions a SavedVariables file" pattern:
  // "SavedVariables/WowAHTracker.lua" alone is a constant, non-sensitive
  // filename (the same on every install; already used unredacted all over
  // this repo, e.g. scripts/ingestSavedVariables.ts's SAVED_VARIABLES_FILE
  // and CLAUDE.md). The actually sensitive case - a real account folder in
  // the path - is caught by the WTF\Account pattern above; an actually
  // *committed* SavedVariables file (not just a text mention of the name)
  // is caught by FORBIDDEN_PATH_PATTERNS. Tried a free-text version of this
  // and reverted it 2026-09-28: it fired on a commit message that only
  // ever mentioned the filename, never contained a real path.
];

interface Hit {
  where: string;
  label: string;
  masked: string;
}

function git(args: string[]): string {
  return execFileSync("git", args, { cwd: REPO_ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
}

function mask(term: string): string {
  if (term.length <= 2) return "*".repeat(term.length);
  return term[0] + "*".repeat(term.length - 2) + term[term.length - 1];
}

function loadDenylistTerms(): string[] {
  const terms = new Set<string>();
  if (existsSync(PRIVATE_TERMS_PATH)) {
    for (const line of readFileSync(PRIVATE_TERMS_PATH, "utf8").split("\n")) {
      const t = line.trim();
      if (t && !t.startsWith("#")) terms.add(t);
    }
  } else {
    console.warn(
      `WARNING: ${PRIVATE_TERMS_PATH} doesn't exist - run "npm run ingest" at least once. ` +
        "Continuing with generic patterns and config/earningsAccounts.local.json only.",
    );
  }
  if (existsSync(LOCAL_ACCOUNTS_PATH)) {
    try {
      const parsed: unknown = JSON.parse(readFileSync(LOCAL_ACCOUNTS_PATH, "utf8"));
      if (Array.isArray(parsed)) {
        for (const a of parsed) {
          // folder only - the account LABEL is deliberately excluded (see
          // src/privacy/privateTerms.ts): low sensitivity, and a generic
          // label like "Account 1" collides with
          // config/earningsAccounts.example.json's own placeholder text.
          if (a && typeof a.folder === "string" && a.folder) terms.add(a.folder);
        }
      }
    } catch {
      // Malformed local config isn't this script's problem to report.
    }
  }
  return [...terms];
}

/**
 * Whole-"word" match: not preceded/followed by a letter or digit. Case-insensitive.
 *
 * Deliberately does NOT treat an apostrophe as continuing the word on either
 * side of the match: a term like "Anub'arak" still matches correctly because
 * its own internal apostrophe is part of the literal (escaped) match text,
 * not part of this boundary check. Bug found and fixed 2026-09-28: an
 * earlier version DID exclude apostrophe here "for compound names," which
 * was never needed for that reason and had a real cost - it also made a
 * possessive (e.g. "Someaccount's") continue the word, so the term
 * "Someaccount" silently failed to match inside "Someaccount's export".
 * Found by manually re-checking a commit the deep review had already
 * flagged, which this script reported as clean.
 */
export function findTermHits(text: string, term: string): boolean {
  const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const re = new RegExp(`(?<![\\p{L}\\p{N}])${escaped}(?![\\p{L}\\p{N}])`, "iu");
  return re.test(text);
}

function scanTextForTerms(text: string, where: string, terms: string[], hits: Hit[]): void {
  for (const term of terms) {
    if (findTermHits(text, term)) {
      hits.push({ where, label: "private term", masked: mask(term) });
    }
  }
  for (const { label, re } of GENERIC_PATTERNS) {
    const m = text.match(re);
    if (m) hits.push({ where, label, masked: mask(m[0]) });
  }
}

/** Parses `git diff --unified=0`, returning only added lines with their file + line number. */
function scanDiffAddedLines(diffRange: string | null, staged: boolean, terms: string[], hits: Hit[]): void {
  const args = staged
    ? ["diff", "--cached", "--unified=0", "--"]
    : ["diff", "--unified=0", diffRange as string, "--"];
  let diff: string;
  try {
    diff = git(args);
  } catch (err) {
    throw new Error(`git ${args.join(" ")} failed: ${(err as Error).message}`);
  }

  let currentFile = "(unknown file)";
  let nextLine = 0;
  for (const line of diff.split("\n")) {
    if (line.startsWith("+++ ")) {
      const p = line.slice(4).trim();
      currentFile = p === "/dev/null" ? "(deleted)" : p.replace(/^b\//, "");
      continue;
    }
    const hunk = line.match(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@/);
    if (hunk) {
      nextLine = parseInt(hunk[1], 10);
      continue;
    }
    if (line.startsWith("+") && !line.startsWith("+++")) {
      scanTextForTerms(line.slice(1), `${currentFile}:${nextLine}`, terms, hits);
      nextLine++;
    } else if (!line.startsWith("-") && !line.startsWith("\\")) {
      // context line under --unified=0 shouldn't occur, but keep the counter honest if it does
      nextLine++;
    }
  }
}

function scanCommitMessages(range: string, terms: string[], hits: Hit[]): void {
  const SEP = "\x03";
  let out: string;
  try {
    out = git(["log", range, `--format=%H%x00%B${SEP}`]);
  } catch (err) {
    throw new Error(`git log ${range} failed: ${(err as Error).message}`);
  }
  for (const record of out.split(SEP)) {
    if (!record.trim()) continue;
    const nul = record.indexOf("\0");
    if (nul < 0) continue;
    const sha = record.slice(0, nul).trim();
    const message = record.slice(nul + 1);
    scanTextForTerms(message, `commit message ${sha.slice(0, 10)}`, terms, hits);
  }
}

function scanPathsForForbidden(range: string | null, staged: boolean, hits: Hit[]): void {
  const args = staged ? ["diff", "--cached", "--name-only", "--diff-filter=ACMR"] : ["diff", "--name-only", "--diff-filter=ACMR", range as string];
  let out: string;
  try {
    out = git(args);
  } catch (err) {
    throw new Error(`git ${args.join(" ")} failed: ${(err as Error).message}`);
  }
  for (const p of out.split("\n").map((l) => l.trim()).filter(Boolean)) {
    for (const pat of FORBIDDEN_PATH_PATTERNS) {
      if (pat.test(p)) {
        hits.push({ where: p, label: "path that .gitignore normally excludes", masked: p });
      }
    }
  }
}

function scanRange(range: string, terms: string[]): Hit[] {
  const hits: Hit[] = [];
  scanDiffAddedLines(range, false, terms, hits);
  scanCommitMessages(range, terms, hits);
  scanPathsForForbidden(range, false, hits);
  return hits;
}

function scanStaged(terms: string[]): Hit[] {
  const hits: Hit[] = [];
  scanDiffAddedLines(null, true, terms, hits);
  scanPathsForForbidden(null, true, hits);
  return hits;
}

function report(hits: Hit[]): void {
  console.error("\nPersonal-data guard: BLOCKED - possible private data found in what you're about to commit/push:\n");
  for (const h of hits) {
    console.error(`  ${h.where}: ${h.label} (${h.masked})`);
  }
  console.error(
    "\nIf this is a false positive, fix the underlying text (this repo is public - see CLAUDE.md #8/#13) " +
      "rather than bypassing the check.\n",
  );
}

function main(): void {
  const argv = process.argv.slice(2);
  const terms = loadDenylistTerms();

  if (argv.includes("--staged")) {
    const hits = scanStaged(terms);
    if (hits.length > 0) {
      report(hits);
      process.exitCode = 1;
    }
    return;
  }

  const rangeIdx = argv.indexOf("--range");
  if (rangeIdx >= 0) {
    const range = argv[rangeIdx + 1];
    if (!range) throw new Error("--range requires a value, e.g. --range abc123..def456");
    const hits = scanRange(range, terms);
    if (hits.length > 0) {
      report(hits);
      process.exitCode = 1;
    }
    return;
  }

  // Default: git's pre-push protocol on stdin.
  const stdin = readFileSync(0, "utf8");
  const lines = stdin.split("\n").map((l) => l.trim()).filter(Boolean);
  if (lines.length === 0) {
    // Nothing to check (e.g. deleting a remote ref only, or invoked with no input).
    return;
  }

  const allHits: Hit[] = [];
  for (const line of lines) {
    const parts = line.split(/\s+/);
    if (parts.length !== 4) continue;
    const [, localSha, , remoteSha] = parts;
    if (localSha === ALL_ZERO) continue; // deleting the remote ref - nothing new to scan
    const base = remoteSha === ALL_ZERO ? EMPTY_TREE : remoteSha;
    const range = `${base}..${localSha}`;
    allHits.push(...scanRange(range, terms));
  }

  if (allHits.length > 0) {
    report(allHits);
    process.exitCode = 1;
  }
}

// Only run when executed directly (as the git hook or via npx tsx), never on
// import - scripts/checkPrivateData.test.ts imports findTermHits from this
// file, and without this guard that import alone would trigger a full CLI
// run, including a blocking read of stdin (default pre-push protocol mode),
// which hangs the test runner forever (found the hard way: a supposedly-fast
// test run hung until manually killed).
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  main();
}
